/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pacote;

import ferramentas.CaixaDeDialogo;



/**
 *
 * @author Leonardo
 */
public class InterfaceBanco extends javax.swing.JFrame {

    /**
     * Creates new form InterfaceBanco
     */
    Conta conta1;
    Conta conta2;
    public InterfaceBanco() {
        initComponents();
        
      ;
        
    }
    private void atualizarInformacoesTela(){
        ContaController controller = new ContaController();
        float saldoConta1 = controller.buscarSaldo(conta1.getId());
        float saldoConta2 = controller.buscarSaldo(conta2.getId());
        
        conta1.setSaldo(saldoConta1);
        conta2.setSaldo(saldoConta2);
        
        lblConta1.setText(conta1.getNome());
        lblConta2.setText(conta2.getNome());
        lblChequeEspecialConta1.setText(String.valueOf(conta1.getCheque_especial()));
        lblChequeEspecialConta2.setText(String.valueOf(conta2.getCheque_especial()));
        lblSaldoConta1.setText(String.valueOf(conta1.getSaldo()));
        lblSaldoConta2.setText(String.valueOf(conta2.getSaldo()));
    }
            

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     * so para commit
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblConta1 = new javax.swing.JLabel();
        lblSaldoConta1 = new javax.swing.JLabel();
        btnTransferirConta1 = new javax.swing.JButton();
        tnTransferirConta2 = new javax.swing.JButton();
        txtValorConta1 = new javax.swing.JTextField();
        txtValorConta2 = new javax.swing.JTextField();
        lblConta2 = new javax.swing.JLabel();
        lblSaldoConta2 = new javax.swing.JLabel();
        btnSacarConta1 = new javax.swing.JButton();
        btnDepositarConta1 = new javax.swing.JButton();
        btnSacarConta2 = new javax.swing.JButton();
        btnDespositarConta2 = new javax.swing.JButton();
        lblChequeEspecialConta1 = new javax.swing.JLabel();
        lblChequeEspecialConta2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblConta1.setText("Conta 1");
        getContentPane().add(lblConta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        lblSaldoConta1.setText("Saldo");
        getContentPane().add(lblSaldoConta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 28, -1, -1));

        btnTransferirConta1.setText("Transferir");
        btnTransferirConta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransferirConta1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnTransferirConta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 97, -1, -1));

        tnTransferirConta2.setText("Transferir");
        tnTransferirConta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tnTransferirConta2ActionPerformed(evt);
            }
        });
        getContentPane().add(tnTransferirConta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 97, -1, -1));
        getContentPane().add(txtValorConta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 69, 80, -1));
        getContentPane().add(txtValorConta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 69, 80, -1));

        lblConta2.setText("Conta 2");
        getContentPane().add(lblConta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(382, 7, -1, -1));

        lblSaldoConta2.setText("Saldo");
        getContentPane().add(lblSaldoConta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, -1, -1));

        btnSacarConta1.setText("Sacar");
        btnSacarConta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacarConta1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnSacarConta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 125, 80, -1));

        btnDepositarConta1.setText("Depositar");
        btnDepositarConta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepositarConta1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnDepositarConta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 153, -1, -1));

        btnSacarConta2.setText("Sacar");
        btnSacarConta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacarConta2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnSacarConta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 125, 80, -1));

        btnDespositarConta2.setText("Depositar");
        btnDespositarConta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDespositarConta2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnDespositarConta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 153, -1, -1));

        lblChequeEspecialConta1.setText("Cheque");
        getContentPane().add(lblChequeEspecialConta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 47, -1, -1));

        lblChequeEspecialConta2.setText("Cheque");
        getContentPane().add(lblChequeEspecialConta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(382, 47, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDepositarConta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepositarConta1ActionPerformed
        try{
            float valor = Float.parseFloat(txtValorConta1.getText());
            ContaController controller = new ContaController();
            boolean retorno = controller.debito(conta1.getId(), valor);
            if(retorno){
                atualizarInformacoesTela();
                CaixaDeDialogo.obterinstancia().exibirMensagem("Operação realizada com sucesso", 'i');
                System.out.println("Operação de depósito no valor de R$: " + valor);
            }else{
                CaixaDeDialogo.obterinstancia().exibirMensagem("Erro na operação", 'e');
            }
            
        }catch (Exception ex){
            CaixaDeDialogo.obterinstancia().exibirMensagem("Erro: " + ex.getMessage(), 'e');
        }
    }//GEN-LAST:event_btnDepositarConta1ActionPerformed

    private void btnSacarConta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacarConta1ActionPerformed
      try{
            float valor = Float.parseFloat(txtValorConta1.getText());
            ContaController controller = new ContaController();
            boolean retorno = controller.credito(conta1, valor);
            if(retorno){
                atualizarInformacoesTela();
                CaixaDeDialogo.obterinstancia().exibirMensagem("Operação realizada com sucesso", 'i');
                System.out.println("Operação de saque no valor de R$: " + valor);
            }else{
                CaixaDeDialogo.obterinstancia().exibirMensagem("Erro na operação", 'e');
            }
            
        }catch (Exception ex){
            CaixaDeDialogo.obterinstancia().exibirMensagem("Erro: " + ex.getMessage(), 'e');
        }
    }//GEN-LAST:event_btnSacarConta1ActionPerformed

    private void btnSacarConta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacarConta2ActionPerformed
    try{
            float valor = Float.parseFloat(txtValorConta2.getText());
            ContaController controller = new ContaController();
            boolean retorno = controller.credito(conta2, valor);
            if(retorno){
                atualizarInformacoesTela();
                CaixaDeDialogo.obterinstancia().exibirMensagem("Operação realizada com sucesso", 'i');
                System.out.println("Operação de saque no valor de R$: " + valor);
            }else{
                CaixaDeDialogo.obterinstancia().exibirMensagem("Erro na operação", 'e');
            }
            
        }catch (Exception ex){
            CaixaDeDialogo.obterinstancia().exibirMensagem("Erro: " + ex.getMessage(), 'e');
        }
    }//GEN-LAST:event_btnSacarConta2ActionPerformed

    private void btnDespositarConta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDespositarConta2ActionPerformed
         try{
            float valor = Float.parseFloat(txtValorConta2.getText());
            ContaController controller = new ContaController();
            boolean retorno = controller.debito(conta2.getId(), valor);
            if(retorno){
                atualizarInformacoesTela();
                CaixaDeDialogo.obterinstancia().exibirMensagem("Operação realizada com sucesso", 'i');
                System.out.println("Operação de depósito no valor de R$: " + valor);
            }else{
                CaixaDeDialogo.obterinstancia().exibirMensagem("Erro na operação", 'e');
            }
            
        }catch (Exception ex){
            CaixaDeDialogo.obterinstancia().exibirMensagem("Erro: " + ex.getMessage(), 'e');
        }
    }//GEN-LAST:event_btnDespositarConta2ActionPerformed

    private void btnTransferirConta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransferirConta1ActionPerformed
        try{
            float valor = Float.parseFloat(txtValorConta1.getText());
            ContaController controller = new ContaController();
            boolean retorno = controller.credito(conta1, valor);
            if(retorno){
                controller.debito(conta2.getId(), valor);
                atualizarInformacoesTela();
                CaixaDeDialogo.obterinstancia().exibirMensagem("Operação realizada com sucesso", 'i');
                System.out.println("Operação de transferencia no valor de R$: " + valor);
            }else{
                CaixaDeDialogo.obterinstancia().exibirMensagem("Erro na operação", 'e');
            }
            
        }catch (Exception ex){
            CaixaDeDialogo.obterinstancia().exibirMensagem("Erro: " + ex.getMessage(), 'e');
        }
    }//GEN-LAST:event_btnTransferirConta1ActionPerformed

    private void tnTransferirConta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tnTransferirConta2ActionPerformed
        try{
            float valor = Float.parseFloat(txtValorConta2.getText());
            ContaController controller = new ContaController();
            boolean retorno = controller.credito(conta2, valor);
            if(retorno){
                controller.debito(conta1.getId(), valor);
                atualizarInformacoesTela();
                CaixaDeDialogo.obterinstancia().exibirMensagem("Operação realizada com sucesso", 'i');
                System.out.println("Operação de transferencia no valor de R$: " + valor);
            }else{
                CaixaDeDialogo.obterinstancia().exibirMensagem("Erro na operação", 'e');
            }
            
        }catch (Exception ex){
            CaixaDeDialogo.obterinstancia().exibirMensagem("Erro: " + ex.getMessage(), 'e');
        }
    }//GEN-LAST:event_tnTransferirConta2ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        ContaController controller = new ContaController();
        //conta1 = controller.buscar(1);
        conta2 = controller.buscar(2);
        
        
        
        atualizarInformacoesTela();
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceBanco().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDepositarConta1;
    private javax.swing.JButton btnDespositarConta2;
    private javax.swing.JButton btnSacarConta1;
    private javax.swing.JButton btnSacarConta2;
    private javax.swing.JButton btnTransferirConta1;
    private javax.swing.JLabel lblChequeEspecialConta1;
    private javax.swing.JLabel lblChequeEspecialConta2;
    private javax.swing.JLabel lblConta1;
    private javax.swing.JLabel lblConta2;
    private javax.swing.JLabel lblSaldoConta1;
    private javax.swing.JLabel lblSaldoConta2;
    private javax.swing.JButton tnTransferirConta2;
    private javax.swing.JTextField txtValorConta1;
    private javax.swing.JTextField txtValorConta2;
    // End of variables declaration//GEN-END:variables

    private float gerador(int i) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
